### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by ronaldaraujo** [delta98/ionic-material-design-lite#69] opened 2015-09-01 00:17 UTC
Uncaught TypeError: Cannot read property 'style' of null and
Uncaught TypeError: Cannot read property 'classList' of null

The error happens when I click on one of the tabs.

And the list is cut. Any suggestion?

http://i.imgur.com/ncsGcew.png

My index.html

<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <title></title>

    <link href="lib/ionic/css/ionic.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="css/ionic.material-design-lite.css" rel="stylesheet">
    <script src="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.min.js"></script>

    

    
    <script src="lib/ionic/js/ionic.bundle.js"></script>
    
    <script src="js/ionic.material-design-lite.js"></script>

    
    <script src="cordova.js"></script>

    
    <script src="js/app.js"></script>
    <script src="js/controllers.js"></script>
    <script src="js/services.js"></script>
  </head>
  <body ng-app="starter">
    <ion-nav-bar class="bar-stable">
      <ion-nav-back-button>
      </ion-nav-back-button>
    </ion-nav-bar>
    <ion-nav-view></ion-nav-view>
  </body>
</html>

**Comment by delta98** [comment] 2015-09-01 06:58
Hi @ronaldaraujo this is already being tracked #49 its caused by Google's MDL library for tabs. Nothing to worry about, you've implemented tabs correctly, it's a library issue I'm trying to resolve with them.

**Comment by delta98** [comment] 2015-09-01 06:58
Closing as duplicated #49

**Closed by delta98** 2015-09-01 06:58 UTC
Labels: bug, duplicate
