### ISSUE TITLE
Effects not work

### ISSUE THREAD

**Issue by protasisimone** [delta98/ionic-material-design-lite#62] opened 2015-08-26 14:38 UTC
Hi, I've installed with bower.
I added the css and js file in head and i've tried to create a button but the ripple effect doesn't work, can you suggest me a correct way to do his work?

This is my code in `<ion-nav-bar>`:
```
<ion-nav-buttons side="right">
    // Other code
    <button class="button icon ion-heart button-icon" ng-click="popover.show($event)">
    </button>
</ion-nav-buttons>
```

Thanks!

**Comment by delta98** [comment] 2015-08-26 16:19
Looks like you have it setup correctly, are you able to markup a button outside of the `ion-nav-buttons` directive and see if the effects work?

**Comment by protasisimone** [comment] 2015-08-31 09:27
Thanks for your reply.

I had try outside the `ion-nav-buttons` but doesn't work.

Any ideas?

**Comment by delta98** [comment] 2015-09-02 09:10
Sorry, it's hard to understand what the problem is. Can you please explain how you have setup your app with the project.

**Comment by protasisimone** [comment] 2015-09-02 09:58
Ok, I'm sorry but my english is very bad.

The ripple effect does not work when the button is inserted in `ion-nav-buttons` directive.

I think it's a matter of css.
```
<!DOCTYPE html>
<html ng-app="starter">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
		<title></title>
		
		<!-- Css -->
		<link href="lib/ionic/css/ionic.css" rel="stylesheet">
		<link href="lib/ionic-material-design-lite/dist/ionic.material-design-lite.css" rel="stylesheet">
		<link href="css/style.css" rel="stylesheet">
		
		<!-- Javascript -->
		<script src="lib/ionic/js/ionic.bundle.js"></script>
		<script src="lib/ionic-material-design-lite/dist/ionic.material-design-lite.js"></script>
		<script src="lib/ngCordova/dist/ng-cordova.js"></script>
		<script src="cordova.js"></script>
		<script src="js/app.js"></script>

	</head>
	<body ng-controller="AppController">

		<ion-nav-bar class="bar-assertive">
			<!-- Back button -->
			<ion-nav-back-button class="button-clear">
			</ion-nav-back-button>
			
			<!-- Nav button -->
			<ion-nav-buttons side="right">
				<button class="button icon ion-heart button-icon"></button>
			</ion-nav-buttons>


		</ion-nav-bar>
		
		<ion-nav-view>
		</ion-nav-view>
	</body>
</html>
```

This is my `index.html` code.

**Comment by adyba** [comment] 2015-09-02 12:17
I do believe its not a bug. The ripple effect doesn't work in a standard web preview. You have to emulate an Android device. Jason's CodePen example fires a native like behavior by using extra code that is not part of the git package.

Use my Ionic plunk http://plnkr.co/edit/P2nauG launch the `preview in a separated window` and emulate an Android device (you should probably refresh the preview window). The code spits some errors but works.

**Comment by delta98** [comment] 2015-09-02 12:25
Thanks @adyba 

What is the extra behaviour you are referring to? Is it the `platform-override`/`platform-android` class added to body?

More info here: https://github.com/delta98/ionic-material-design-lite#override-styles-for-both-platforms-iosandroid

**Comment by adyba** [comment] 2015-09-02 13:15
Once I have played with a Ionic starter I realized that that sometimes the standard web server started with `ionic serve` doesn't provide the full ripple effect (just standard CSS). Same window with Android emulation was OK. I haven't look through the CodePen in detail but there is a bunch of code in the JS pane that I suspected to be a reason why It works in plain web view. 
As a Ionic developer I don't mind if something doesn't work on desktop but works on device/emulator of kind. Thus I believe it is not a bug and it will be solved after several iterations.
P.S. After I updated to the most current version 0.5.5 it works fine even on web.

**Comment by delta98** [comment] 2015-09-02 15:10
Thanks for your feedback, really important to the project. I'll now close this issue.

**Closed by delta98** 2015-09-02 15:10 UTC
Labels: help wanted

**Comment by protasisimone** [comment] 2015-09-03 14:51
Thanks for support but i don't understanding this.

For iOS, the ripple effect doesn't work? I've try on emulator and this effect doesn't work.

Solutions?

**Comment by protasisimone** [comment] 2015-09-03 15:06
Ok. I just made a trial run on iOs and Android smartphones.

Android does everything perfectly. Of IOS, only it works on `button icon` while the other buttons have no ripple effect.

I also confirm that Android runs the effect on the `nav-bar` in the `nav-buttons`, iOS does not.

I hope I have contributed a minimum to achieve the goals of this project.

Do you already have in mind how to solve uniformly viewing on both systems?

**Comment by delta98** [comment] 2015-09-03 17:18
iOS **should not** by default be displayed as Material Design. To enable for both platforms you should read the following instructions https://github.com/delta98/ionic-material-design-lite#override-styles-for-both-platforms-iosandroid

**Comment by protasisimone** [comment] 2015-09-05 08:40
@delta98 I had enabled the override for this test.
Those written above , are the results

**Comment by helmuthva** [comment] 2015-09-12 12:36
Hi,

seems that

          this.useMaterialIcons = true;
          this.useMaterialRipple = true;

is missing in this.enableForAllPlatforms = function () {...} to make the ripple effect work for all plattforms ..
